const cobissData = [
  { descr: "Brina Brihta", author: "Rippin, Sally", totalCount: 1393 },
  { descr: "Macek Muri", author: "Kovic, Kajetan", totalCount: 1106 },
  { descr: "Vse zivali druzine Cmok", author: "Gomboc, Mateja", totalCount: 1076 },
  { descr: "Drejcek in trije Marsovccki", author: "Pecjak, Vid", totalCount: 1046 },
  { descr: "Svrk", author: "Moderndorfer, Vinko", totalCount: 970 },
  { descr: "Povodni moz", author: "Preseren, France", totalCount: 966 },
  { descr: "Belo se pere na devetdeset", author: "Zakelj, Bronja", totalCount: 812 },
  { descr: "Solzice", author: "Prezihov Voranc", totalCount: 785 },
  { descr: "Zlocin in kazen", author: "Dostoevskij, F. M.", totalCount: 736 },
  { descr: "Decek Brin na domacem koliscu", author: "Pregelj, Sebastijan", totalCount: 698 },
  { descr: "Kosarkar naj bo!", author: "Suhodolcan, Primoz", totalCount: 697 },
  { descr: "Gringo Loco", author: "Doma, Simon", totalCount: 685 },
  { descr: "Matilda", author: "Dahl, Roald", totalCount: 663 },
  { descr: "Pasji moz, Skrlatni dlakac", author: "Pilkey, Dav", totalCount: 652 },
  { descr: "Brezno", author: "Golob, Tadej", totalCount: 648 },
  { descr: "Pasji moz, Materin vrh", author: "Pilkey, Dav", totalCount: 648 },
  { descr: "Majnice", author: "Pavcek, Tone", totalCount: 644 },
  { descr: "Pasji moz, Ravs divjine", author: "Pilkey, Dav", totalCount: 635 },
  { descr: "Pasji moz", author: "Pilkey, Dav", totalCount: 634 },
  { descr: "Pasji moz, Veliki Joza na zacetku", author: "Pilkey, Dav", totalCount: 628 },
  { descr: "Pasji moz, Snet s ketne", author: "Pilkey, Dav", totalCount: 625 },
  { descr: "Pasji moz, Dvajset tisoc bolh", author: "Pilkey, Dav", totalCount: 609 },
  { descr: "Pasji moz, 22 kaveljcev", author: "Pilkey, Dav", totalCount: 608 },
  { descr: "Pasji moz in Macji mulc", author: "Pilkey, Dav", totalCount: 608 },
  { descr: "Pasji moz, Gospodar bolh", author: "Pilkey, Dav", totalCount: 607 },
  { descr: "Pasji moz, Kazin in kazen", author: "Pilkey, Dav", totalCount: 605 },
  { descr: "Pasji moz, H komu se kotali?", author: "Pilkey, Dav", totalCount: 594 },
  { descr: "Sveza voda za roze", author: "Perrin, Valerie", totalCount: 588 },
  { descr: "Pasji moz, Povest o dveh muckih", author: "Pilkey, Dav", totalCount: 560 },
  { descr: "Visoska kronika", author: "Tavcar, Ivan", totalCount: 558 },
  { descr: "Zverjascek", author: "Donaldson, Julia", totalCount: 499 },
  { descr: "Solski slovar, Anglescina", author: "", totalCount: 466 },
  { descr: "Superdezevnik", author: "Donaldson, Julia", totalCount: 465 },
  { descr: "Stripovski klub Macjega mulca", author: "Pilkey, Dav", totalCount: 448 },
  { descr: "Zgodbe o Presernu", author: "Music, Janez", totalCount: 448 },
  { descr: "Po nebu tecejo reke", author: "Shafak, Elif", totalCount: 446 },
  { descr: "Moje zivljenje", author: "Cankar, Ivan", totalCount: 443 },
  { descr: "Se spomnis?", author: "McFadden, Freida", totalCount: 441 },
  { descr: "Pod medvedovim deznikov", author: "Makarovic, Svetlana", totalCount: 438 },
  { descr: "Romeo in Julija", author: "Shakespeare, William", totalCount: 433 },
  { descr: "Bratovscina Sinjega galeba", author: "Selisar, Tone", totalCount: 432 },
  { descr: "Antigona; Kralj Ojdipus", author: "Sophocles", totalCount: 431 },
  { descr: "Muca Copatarica", author: "Peroci, Ela", totalCount: 427 },
  { descr: "Hisna pomocnica", author: "McFadden, Freida", totalCount: 426 },
  { descr: "Zverjasec", author: "Donaldson, Julia", totalCount: 422 },
  { descr: "Stripovski klub Macjega mulca, Poslanstvo", author: "Pilkey, Dav", totalCount: 420 },
  { descr: "Bi se gnetli na tej metli?", author: "Donaldson, Julia", totalCount: 417 },
  { descr: "Stare grske bajke", author: "Petiska, Eduard", totalCount: 414 },
  { descr: "Tako zelo vas imam rada", author: "Ogulin, Anita", totalCount: 408 },
  { descr: "Dogodek v mestu Gogi", author: "Grum, Slavko", totalCount: 407 },
  { descr: "Babica v supergah", author: "Mate, Miha", totalCount: 404 },
  { descr: "Najemnica", author: "McFadden, Freida", totalCount: 403 },
  { descr: "Izbranec", author: "McFadden, Freida", totalCount: 399 },
  { descr: "Pedenjped", author: "Grafenauer, Niko", totalCount: 390 },
  { descr: "Palcic", author: "Donaldson, Julia", totalCount: 389 },
  { descr: "Kaksno drevo zraste iz macka", author: "Konc Lorenzutti, Natasa", totalCount: 380 },
  { descr: "Stripovski klub Macjega mulca, Perspektive", author: "Pilkey, Dav", totalCount: 379 },
  { descr: "Zog", author: "Donaldson, Julia", totalCount: 376 },
  { descr: "Garfield na vrhu sveta", author: "Davis, Jim", totalCount: 375 },
  { descr: "Garfield na sprehodu", author: "Davis, Jim", totalCount: 373 },
  { descr: "Ravnateljeva hci", author: "Kamenik, Ana", totalCount: 373 },
  { descr: "Najboljse sele pride", author: "Ujawe, Petra Julia", totalCount: 372 },
  { descr: "Stripovski klub Macjega mulca, Sodelovanje", author: "Pilkey, Dav", totalCount: 372 },
  { descr: "Misji razbojnik", author: "Donaldson, Julia", totalCount: 368 },
  { descr: "Kako pokopati mamo, ki je se ziva?", author: "Ebner, Nadja", totalCount: 367 },
  { descr: "Trk", author: "McFadden, Freida", totalCount: 366 },
  { descr: "Popolni sin", author: "McFadden, Freida", totalCount: 363 },
  { descr: "Voranc : prva knjiga", author: "Partljic, Tone", totalCount: 363 },
  { descr: "Zapornik", author: "McFadden, Freida", totalCount: 363 },
  { descr: "Garfield vam jo zakuha", author: "Davis, Jim", totalCount: 359 },
  { descr: "Medvedki sladkosnedki", author: "Kosovel, Srecko", totalCount: 356 },
  { descr: "Garfield na dieti", author: "Davis, Jim", totalCount: 355 },
  { descr: "Juhej, ze berem!", author: "Rot Vrhovec, Alenka", totalCount: 354 },
  { descr: "Hamlet", author: "Shakespeare, William", totalCount: 353 },
  { descr: "Kit na plazi", author: "Moderndorfer, Vinko", totalCount: 351 },
  { descr: "Na klancu", author: "Cankar, Ivan", totalCount: 351 },
  { descr: "Osnove prve pomoci", author: "Malic, Zeljko", totalCount: 351 },
  { descr: "Polz na potepu na kitovem repu", author: "Donaldson, Julia", totalCount: 347 },
  { descr: "Hisna pomocnica opazuje", author: "McFadden, Freida", totalCount: 346 },
  { descr: "Loncek na pike", author: "Stefan, Anja", totalCount: 343 },
  { descr: "Primer srhljive sence", author: "Ohlsson, Kristina", totalCount: 341 },
  { descr: "Skrivnost hisne pomocnice", author: "McFadden, Freida", totalCount: 339 },
  { descr: "Pekarna Mismaz", author: "Makarovic, Svetlana", totalCount: 335 },
  { descr: "Kosovirja na leteci zlici", author: "Makarovic, Svetlana", totalCount: 332 },
  { descr: "Ronja, razbojniska hci", author: "Lindgren, Astrid", totalCount: 328 },
  { descr: "Anica in grozovitez", author: "Muck, Desa", totalCount: 327 },
  { descr: "Mehurcki", author: "Zupancic, Oton", totalCount: 327 },
  { descr: "Tam, kjer plesejo tulipani", author: "Svetek, Irena", totalCount: 326 },
  { descr: "Ljubezen mojega zivljenja", author: "Walsh, Rosie", totalCount: 325 },
  { descr: "Zog in leteca zdravnika", author: "Donaldson, Julia", totalCount: 325 },
  { descr: "Sodelavka", author: "McFadden, Freida", totalCount: 322 },
  { descr: "Otok pogresanih dreves", author: "Shafak, Elif", totalCount: 321 },
  { descr: "Obzalovanje", author: "Hoover, Colleen", totalCount: 319 },
  { descr: "Primer hudobne igre", author: "Ohlsson, Kristina", totalCount: 317 },
  { descr: "Uciteljica", author: "McFadden, Freida", totalCount: 316 },
  { descr: "V drugi kozi", author: "Xander, Iliana", totalCount: 313 },
  { descr: "Nikoli ne lazi", author: "McFadden, Freida", totalCount: 312 },
  { descr: "Primer skrivnostne sladkorne posasti", author: "Ohlsson, Kristina", totalCount: 309 },
  { descr: "Harry Potter, Kamen modrosti", author: "Rowling, J. K.", totalCount: 308 },
  { descr: "Moje izgubljeno dekle", author: "Hoover, Colleen", totalCount: 307 }
];